[tools]
usage = "latest"
slsa-verifier = "latest"
cosign = "latest"
cargo-binstall = "latest"
difftastic = "latest"
eza = "latest"
tokei = "latest"
rust = "latest"
ruby = "latest"
node = "latest"
python = "latest"
uv = "latest"
go = "latest"
fzf = "latest"
bat = "latest"
"cargo:tealdeer" = "latest"
"pipx:lizard" = "latest"

[settings]
activate_aggressive = true
idiomatic_version_file_enable_tools = ["node"]
